version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
