pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Travis CI - Pull Request
      - base=develop
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: {}

  - name: automatic merge for Dependabot preview pull requests
    conditions:
      - author=dependabot-preview[bot]
      - check-success=Travis CI - Pull Request
      - base=develop
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: {}
