language: node_js
node_js:
- node
cache:
  yarn: true
notifications:
  email:
    recipients:
    - owlbeardm@gmail.com
install:
- yarn
  #- yarn install --force
script:
- echo "skipping tests"
  #- yarn test
